version: "3.8"
services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: infra/docker/prod/Dockerfile.backend
        image: backend_image
        tty: true
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env  
        volumes:
            - type: bind
              source: ./backend/app
              target: /go/src/app
        networks:
            - frontend_network
            - backend_network

    db:
        container_name: db
        build:
            context: ./infra/docker/prod
            dockerfile: Dockerfile.db
        image: db_image
        tty: true
        platform: linux/x86_64
        ports:
            - 3306:3306
        env_file:
            - .env  
        volumes:
            - mysql_test_volume:/var/lib/mysql
        networks:
            - backend_network
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
            
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./infra/docker/prod/Dockerfile.frontend
        image: frontend_image
        volumes:
        - ./frontend:/app
        env_file:
        - .env          
        networks:
        - frontend_network
        ports:
        - '80:80'
        
volumes:
    mysql_test_volume:
    node_modules:

networks:
    frontend_network: 
    backend_network: 