version: "3.8"
services:   
    backend:
        container_name: backend
        build:
            context: ./infra/docker
            dockerfile: Dockerfile.backend
        image: backend_image
        tty: true
        ports:
            - "8080:8080"
        depends_on:
            - db
        volumes:
            - type: bind
              source: ./backend/app
              target: /go/src/app
        networks:
            - frontend_network
            - backend_network

    db:
        container_name: db
        build:
            context: ./infra/docker
            dockerfile: Dockerfile.db
        image: db_image
        tty: true
        platform: linux/x86_64
        ports:
            - 3306:3306
        env_file:
            - .env  
        volumes:
            - mysql_test_volume:/var/lib/mysql
        networks:
            - backend_network
            
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./infra/docker/Dockerfile.frontend
        image: frontend_image
        volumes:
        - ./frontend:/app
        networks:
        - frontend_network
        ports:
        - '5173:5173'
        command: >
            sh -c "npm install && npm run dev -- --host"

    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: infra/docker/Dockerfile.nginx
        image: nginx_image
        ports:
            - '80:80'
        networks:
            - frontend_network
        depends_on:
            - frontend

volumes:
    mysql_test_volume:
    node_modules:

networks:
    frontend_network: 
    backend_network: 