FROM node:18

WORKDIR /app

# Ensure the correct path for copying package.json files
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./

RUN npm install

ENV PORT 5173

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]