name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest  # 実行環境を指定
    steps:
      - name: AWSの認証情報を設定
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  

      - name: EC2インスタンスにSSH接続
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOSTNAME }}
          USER: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << 'EOF'
            echo "EC2インスタンスに接続成功"
          EOF

      - name: Deploy to production (dummy)
        run: echo "本番環境にデプロイしています（ダミー）"