name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/jobs/lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/jobs/test.yml

  build:
    needs: test
    uses: ./.github/workflows/jobs/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/jobs/deploy.yml
    secrets: inherit